# Generated by Django 2.2.7 on 2019-11-20 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, verbose_name='databasekey')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('blend_file', models.FileField(blank=True, default=None, null=True, upload_to='instrument/blend/')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='instrument/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, verbose_name='databasekey')),
                ('title', models.CharField(max_length=100)),
                ('midi', models.FileField(blank=True, default=None, null=True, upload_to='music/midi/')),
                ('audio', models.FileField(blank=True, default=None, null=True, upload_to='music/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, verbose_name='databasekey')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('blend_file', models.FileField(blank=True, default=None, null=True, upload_to='player/blend/')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='player/images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', imagekit.models.fields.ProcessedImageField(upload_to='user/images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, verbose_name='databasekey')),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('is_complete', models.BooleanField()),
                ('in_progress', models.BooleanField()),
                ('progress', models.PositiveSmallIntegerField(null=True)),
                ('deliverable', models.URLField(blank=True, default=None, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvvroot.Instrument')),
                ('music_pkg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvvroot.Music')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvvroot.Player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
