# Generated by Django 2.2.7 on 2019-11-20 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, verbose_name='databasekey')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='music/vidio/')),
            ],
        ),
    ]
