# Generated by Django 2.2.7 on 2019-11-21 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, verbose_name='databasekey')),
                ('status', models.CharField(default='PENDING', max_length=64, verbose_name='status')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvvroot.Order')),
            ],
        ),
    ]
