# Generated by Django 2.2.7 on 2019-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0003_blender'),
    ]

    operations = [
        migrations.AddField(
            model_name='blender',
            name='frame_end',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='blender',
            name='frame_start',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
