# Generated by Django 2.2.7 on 2019-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0005_auto_20191121_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
