# Generated by Django 2.2.7 on 2019-11-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0006_auto_20191121_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='codec',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='music/video/'),
        ),
    ]
