# Generated by Django 2.2.7 on 2019-11-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0007_auto_20191121_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blender',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Blender agent pending'), ('REQUESTED', 'Blender agent requested'), ('STARTING', 'Blender agent starting'), ('RUNNING', 'Blender agent running'), ('ENDING', 'Blender agent ending'), ('ENDED', 'Blender agent ending')], default='PENDING', max_length=32, verbose_name='status'),
        ),
    ]
