# Generated by Django 2.2.7 on 2019-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0008_auto_20191122_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
