# Generated by Django 2.2.7 on 2019-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0009_video_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_uri',
        ),
        migrations.AddField(
            model_name='blender',
            name='pid',
            field=models.IntegerField(default=-1),
        ),
    ]
