# Generated by Django 2.2.7 on 2019-12-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0010_auto_20191128_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_frame',
            field=models.PositiveSmallIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='order',
            name='start_frame',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
