# Generated by Django 2.2.7 on 2019-12-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0011_auto_20191202_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='thumbnail',
            new_name='thumbnail_orig',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='thumbnail',
            new_name='thumbnail_orig',
        ),
    ]
