# Generated by Django 2.2.7 on 2020-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0012_auto_20191205_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='midi_track',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
