# Generated by Django 2.2.7 on 2020-01-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0013_order_midi_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frames_per_second',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
