# Generated by Django 2.2.7 on 2020-01-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0015_framespersecond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='frames_per_second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvvroot.FramesPerSecond'),
        ),
    ]
