# Generated by Django 2.2.7 on 2020-01-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0016_auto_20200109_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framespersecond',
            name='fps',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
