# Generated by Django 2.2.7 on 2020-01-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0019_auto_20200116_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='midi_track_left_foot',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='order',
            name='midi_track_right_foot',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='order',
            name='midi_track_right_hand',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
