# Generated by Django 2.2.7 on 2020-01-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0022_auto_20200119_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='classname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tvvroot.InstrumentMap'),
            preserve_default=False,
        ),
    ]
