# Generated by Django 2.2.7 on 2020-01-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0023_instrument_classname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='classname',
            new_name='instrumentmap',
        ),
    ]
