# Generated by Django 2.2.7 on 2020-01-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0024_auto_20200120_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='instrumentmap',
            new_name='classname',
        ),
    ]
