# Generated by Django 2.2.7 on 2020-01-20 13:10
from django.db import migrations, models

"""
def install_instrument_classnames(apps, schema_editor):
    ## Install TVV MIA class names
    INSTRUMENT_CLASSNAMES = [['Bass', None], ['HofnerBass', None], ['UprightBass', None], ['Guitar', None], ["LeadGuitar", None], 
                             ['RhythmGuitar', None],['AccousticGuitar', None], ['ClassicalGuitar', None], ['FolkGuitar', None], 
                             ['Piano', 'left hand, right hand'], ['HammondB3', 'left hand, right hand'], ['Trombone', None], 
                             ['Trumpet', None], ['AltoSax', None], ['DrumKit', 'left hand, right hand, left foot, right foot'], 
                             ['ElectroniDrumKit', 'left hand, right hand, left foot, right foot'], ['Violin', None], ['Viola', None],
                             ['Cello', None], ['Fiddle', None], ['Vibrophone', None], ['Marimba', None]
                            ]
    IM = apps.get_model('tvvroot', 'InstrumentMap')
    for item in INSTRUMENT_CLASSNAMES:
        cn = item[0]
        limbs = item[1]
        im = IM.objects.get(classname=cn)
        im.limbs = limbs
        im.save()
"""
class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0025_auto_20200120_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentmap',
            name='limbs',
            field=models.CharField(default=None, max_length=100, null=True),
        )
#        ,
#        migrations.RunPython(install_instrument_classnames),

    ]
