# Generated by Django 2.2.7 on 2020-01-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0027_auto_20200120_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midi',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvvroot.Music'),
        ),
    ]
