# Generated by Django 2.2.7 on 2020-01-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0028_auto_20200121_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='midi_track_left_foot',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_left_hand',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_right_foot',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_right_hand',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
