# Generated by Django 2.2.7 on 2020-01-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0029_auto_20200122_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='midi_track_left_foot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='midi_track_right_foot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='midi_track_right_hand',
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_left_hand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tvvroot.MIDI'),
        ),
    ]
