# Generated by Django 2.2.7 on 2020-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0030_auto_20200122_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='midi_track_left_hand',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
