# Generated by Django 2.2.7 on 2020-01-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0031_auto_20200122_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='midi_track_left_hand',
            field=models.ForeignKey(default=None, limit_choices_to='self.music_pkg.pk', on_delete=django.db.models.deletion.CASCADE, to='tvvroot.MIDI'),
        ),
    ]
