# Generated by Django 2.2.7 on 2020-01-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0032_auto_20200122_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='midi_track_left_foot',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='midi_track_right_foot',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='midi_track_right_hand',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_left_hand',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
