# Generated by Django 2.2.7 on 2020-01-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvvroot', '0033_auto_20200123_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UXOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tvvroot.Order')),
                ('track_for_left_hand', models.PositiveSmallIntegerField(default=None)),
            ],
            bases=('tvvroot.order',),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvvroot.InstrumentMap'),
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_left_foot',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_left_hand',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_right_foot',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='midi_track_right_hand',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
