# Generated by Django 2.2.7 on 2019-11-15 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tvvspa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='uudi',
        ),
        migrations.AddField(
            model_name='music',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, verbose_name='databasekey'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, verbose_name='databasekey'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, verbose_name='databasekey'),
        ),
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, verbose_name='databasekey'),
        ),
    ]
