# Generated by Django 2.2.7 on 2019-11-15 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvvspa', '0003_auto_20191115_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='icon',
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', imagekit.models.fields.ProcessedImageField(upload_to='common/images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', imagekit.models.fields.ProcessedImageField(upload_to='player/images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvvspa.Player')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', imagekit.models.fields.ProcessedImageField(upload_to='instrument/images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvvspa.Instrument')),
            ],
        ),
    ]
