# Generated by Django 2.2.7 on 2019-11-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvvspa', '0004_auto_20191115_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='icon',
        ),
    ]
