# Generated by Django 2.2.7 on 2019-11-15 17:13

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tvvspa', '0005_remove_player_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='blend_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='instrument/blend/'),
        ),
        migrations.AddField(
            model_name='player',
            name='blend_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='player/blend/'),
        ),
        migrations.AlterField(
            model_name='instrumentphoto',
            name='photos',
            field=imagekit.models.fields.ProcessedImageField(upload_to='instrument/images/'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photos',
            field=imagekit.models.fields.ProcessedImageField(upload_to='user/images/'),
        ),
    ]
